image: atlassian/default-image:2
options:
  size: 2x
definitions:
  caches:
    package-node: ./node_modules
lint: &lint
  - step:
      caches:
        - package-node
      # read more https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html#Configurebitbucket-pipelines.yml-ci_size
      size: 2x
      name: install nodejs and yarn
      script:
        # Get ip address
        # https://askubuntu.com/questions/560412/displaying-ip-address-on-eth0-interface/560415
        - ip addr show
        - apt update && apt install -y netcat
        - |
          # Install Nodejs
          nvm install $(cat .nvmrc)
          nvm alias default $(cat .nvmrc)
          npm install -g yarn
        - |
          echo 'setup environment'
          export MYIP=`ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`

        - |
          yarn
          echo "lint"
        - yarn run typecheck && yarn run lint
      services:
        - docker
deploy: &deploy
  - step:
      caches:
        - package-node
      # read more https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html#Configurebitbucket-pipelines.yml-ci_size
      size: 2x
      name: install nodejs and yarn
      script:
        # Get ip address
        # https://askubuntu.com/questions/560412/displaying-ip-address-on-eth0-interface/560415
        - ip addr show
        - apt update && apt install -y netcat
        - |
          cd ~
          wget https://github.com/digitalocean/doctl/releases/download/v1.45.1/doctl-1.45.1-linux-amd64.tar.gz
          tar xf ~/doctl-1.45.1-linux-amd64.tar.gz
          mv ~/doctl /usr/local/bin
        - |
          cp ./env/staging.env ./.env
          docker-compose up -d --build wisere
          docker tag wisere registry.digitalocean.com/wisere/wisere
        - |
          doctl auth init -t $DO_KEY
          doctl registry login


      
      services:
        - docker
pipelines:
  default:
    - <<: *lint
    - <<: *deploy
  branches:
    master:
      - <<: *lint
      - <<: *deploy
    develop:
      - step:
          caches:
            - docker # adds docker layer caching
            - package-node
          name: install nodejs and yarn
          script:
            # Get ip address
            # https://askubuntu.com/questions/560412/displaying-ip-address-on-eth0-interface/560415
            - ip addr show
            - apt update && apt install -y netcat
            - |
              # Install Nodejs
              nvm install $(cat .nvmrc)
              nvm alias default $(cat .nvmrc)
            - |
              echo 'setup environment'
              export MYIP=`ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`

            - |
              yarn 
              cat .env
              yarn build

            - yarn run test
          services:
            - docker
      - step:
          name: deploy to server via ssh
          script:
            - mkdir -p ~/.ssh
            - cat my_known_hosts >> ~/.ssh/known_hosts
            - (umask  077 ; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
            - echo $MY_SSH_KEY
            - cat ~/.ssh/id_rsa
            - ssh root@221.133.14.73  -T 'bash -s' < .bitbucket-pineline/deploy.sh 'echo "connected to `host` as user"'
          #   - pipe: atlassian/ssh-run:0.1.1
          #     variables:
          #       SSH_USER: 'root'
          #       SERVER: '221.133.14.73'
          #       MODE: 'script'
          #       SSH_KEY: $MY_SSH_KEY
          #       EXTRA_ARGS: '-t'
          #       COMMAND: 'myscript.sh'
          #       DEBUG: 'v'
