version: "3"

services:
  api-gateway:
    container_name: ${API_GTW_HOST}
    env_file: .env
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${API_GTW_PORT}:${API_GTW_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: ${API_GTW_NAME}
    networks:
      - network
    depends_on:
      - system-service
      - notification-service
      - customer-service
      - staff-service
      - branch-service
  real-time-gateway:
    container_name: ${REAL_TIME_GTW_HOST}
    env_file: .env
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${REAL_TIME_GTW_PORT}:${REAL_TIME_GTW_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: ${REAL_TIME_GTW_NAME}
    networks:
      - network
    depends_on:
      - system-service
      - notification-service
      - customer-service
      - staff-service
      - branch-service

  customer-service:
    env_file: .env
    container_name: ${SVC_CUSTOMER_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${SVC_CUSTOMER_PORT}:${SVC_CUSTOMER_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "customer-service"
    networks:
      - network
    depends_on:
      - system-service
      - notification-service
  branch-service:
    env_file: .env
    container_name: ${SVC_BRANCH_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${SVC_BRANCH_PORT}:${SVC_BRANCH_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "${SVC_BRANCH_HOST}"
    networks:
      - network
    depends_on:
      - system-service
      - notification-service
  staff-service:
    container_name: ${SVC_STAFF_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${SVC_STAFF_PORT}:${SVC_STAFF_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "staff-service"
    networks:
      - network
    depends_on:
      - system-service
      - notification-service
  system-service:
    container_name: ${SVC_SYSTEM_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "system-service"
    networks:
      - network
  notification-service:
    container_name: ${SVC_NOTIFICATION_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "notification-service"
    networks:
      - network
  booking-service:
    env_file: .env
    container_name: ${SVC_BOOKING_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${SVC_BOOKING_PORT}:${SVC_BOOKING_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "${SVC_BOOKING_HOST}"
    networks:
      - network

    sale-service:
    env_file: .env
    container_name: ${SVC_SALE_HOST}
    image: registry.digitalocean.com/wisere/wisere
    restart: always
    ports:
      - "127.0.0.1:${SVC_SALE_PORT}:${SVC_SALE_PORT}"
    environment:
      NODE_ENV: "staging"
      NODE_NAME: "${SVC_SALE_HOST}"
    networks:
      - network    

networks:
  network:
    driver: bridge
