version: 2.1
jobs:
  test:
    machine:
      docker_layer_caching: true
    working_directory: ~/wsr
    steps:
      - checkout
      - run:
          name: Setup Nodejs and Yarn
          command: |
            # Install Nodejs
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            source ~/.bash_profile
            nvm install v13.8.0
            nvm alias default  v13.8.0

            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

            # Install Yarn
            npm install -g yarn@1.22.4

      - restore_cache:
          key: dep-{{ checksum "yarn.lock" }}
      - run:
          name: Install package
          command: yarn
          working_directory: ./
      - save_cache:
          key: dep-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  btd:
    jobs:
      - test
