version: 2.1
orbs:
  doctl: digitalocean/cli@1.0.0
jobs:
  test:
    machine:
      # image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/wsr
    steps:
      - checkout
      - run:
          name: Setup Nodejs and Yarn
          command: |
            # Install Nodejs
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            source ~/.bash_profile
            nvm install v13.8.0
            nvm alias default  v13.8.0

            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

            # Install Yarn
            npm install -g yarn@1.22.4

      - restore_cache:
          key: dep-{{ checksum "yarn.lock" }}
      - run:
          name: Install package
          command: yarn
          working_directory: ./
      - save_cache:
          key: dep-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: setting environemnt variables
          command: |
            export MYIP=`ifconfig eth0 | awk '/inet / {print $2}' | awk -F: '{print $2}'`
            echo "export MYIP=$MYIP" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: launch docker container
          working_directory: ./
          command: |
            yarn run start-docker -d

  build:
    context: myContext
    executor: doctl/default
    working_directory: ~/wsr
    steps:
      - doctl/install
      - run: doctl -v

  deploy:
    machine:
      # image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/wsr
    steps:
      - add_ssh_keys
      - run: |
          ssh root@159.65.137.118 'docker ps'

workflows:
  version: 2
  btd:
    jobs:
      # - test
      - build
      - deploy
